# Generated by Django 2.2.2 on 2019-06-20 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cash', models.FloatField()),
                ('frozen_cash', models.FloatField()),
                ('profit', models.FloatField(help_text='profit made till now')),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Activate'), ('f', 'forbidden'), ('i', 'Inactivate')], default='i', help_text='client status', max_length=1)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['stock'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=20)),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, help_text='last price of the stock', max_digits=5, null=True, verbose_name='最新价')),
                ('low', models.DecimalField(blank=True, decimal_places=2, help_text='lowest price of the stock till now today', max_digits=5, null=True, verbose_name='最低价')),
                ('high', models.DecimalField(blank=True, decimal_places=2, help_text='highest price of the stock till now today', max_digits=5, null=True, verbose_name='最高价')),
                ('limit_up', models.DecimalField(blank=True, decimal_places=2, help_text='limit up of the stock today', max_digits=5, null=True, verbose_name='涨停价')),
                ('limit_down', models.DecimalField(blank=True, decimal_places=2, help_text='limit down of the stock today', max_digits=5, null=True, verbose_name='跌停价')),
                ('volume', models.IntegerField(help_text='Total traded volume of this stock today', verbose_name='交易量')),
                ('amount', models.FloatField(help_text='Total traded amount of this stock today', verbose_name='交易额')),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='OrderBookEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('total_vol', models.IntegerField()),
                ('order_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.OrderBook')),
            ],
            options={
                'ordering': ['order_book', 'entry_price'],
            },
        ),
        migrations.CreateModel(
            name='OrderBookElem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_committed', models.DateTimeField(auto_now_add=True)),
                ('direction_committed', models.CharField(choices=[('s', 'SELL'), ('b', 'BUY')], max_length=1, verbose_name='方向')),
                ('price_committed', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('vol_committed', models.IntegerField(verbose_name='数量')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.BaseClient')),
                ('order_book_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.OrderBookEntry')),
            ],
            options={
                'ordering': ['order_book_entry', 'date_committed'],
            },
        ),
        migrations.AddField(
            model_name='orderbook',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Stock'),
        ),
        migrations.CreateModel(
            name='HoldingElem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=12)),
                ('stock_name', models.CharField(max_length=20)),
                ('vol', models.IntegerField(verbose_name='股票总数量')),
                ('frozen_vol', models.IntegerField(verbose_name='冻结数量')),
                ('available_vol', models.IntegerField(verbose_name='可用数量')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='成本价')),
                ('price_guaranteed', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='保本价')),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, help_text='last price of the stock', max_digits=5, null=True, verbose_name='最新价')),
                ('profit', models.FloatField(verbose_name='盈亏')),
                ('value', models.FloatField(verbose_name='市值')),
                ('date_bought', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.BaseClient')),
                ('stock_corr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Stock')),
            ],
            options={
                'ordering': ['owner', '-date_bought'],
            },
        ),
        migrations.CreateModel(
            name='FocusElem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.BaseClient')),
                ('stock_corr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Stock')),
            ],
            options={
                'ordering': ['owner'],
            },
        ),
        migrations.CreateModel(
            name='CommissionElem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_committed', models.DateTimeField(auto_now_add=True)),
                ('stock_symbol', models.CharField(max_length=12)),
                ('stock_name', models.CharField(max_length=20)),
                ('operation', models.CharField(choices=[('a', 'ASK'), ('b', 'BID'), ('c', 'CANCEL')], default='b', help_text='operation', max_length=1)),
                ('price_committed', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='委托价格')),
                ('vol_committed', models.IntegerField(verbose_name='委托数量')),
                ('price_traded', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='成交价格')),
                ('vol_traded', models.IntegerField(verbose_name='成交数量')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.BaseClient')),
                ('stock_corr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Stock')),
            ],
            options={
                'ordering': ['owner', '-date_committed'],
            },
        ),
    ]
