# Generated by Django 2.2.2 on 2019-07-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseclient',
            name='strategy',
            field=models.CharField(choices=[('n', 'No strategy')], default='n', help_text='client strategy', max_length=1),
        ),
    ]
