# Generated by Django 2.2.2 on 2019-06-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='focuselem',
            name='stock_name',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='focuselem',
            name='stock_symbol',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
