# Generated by Django 2.2.2 on 2019-06-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_baseclient_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseclient',
            name='flexible_cash',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
