# Generated by Django 2.2.2 on 2019-06-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_baseclient_flexible_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbookentry',
            name='entry_direction',
            field=models.CharField(default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='holdingelem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='成本价'),
        ),
        migrations.AlterField(
            model_name='holdingelem',
            name='frozen_vol',
            field=models.IntegerField(default=0, verbose_name='冻结数量'),
        ),
        migrations.AlterField(
            model_name='holdingelem',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='last price of the stock', max_digits=5, null=True, verbose_name='最新价'),
        ),
        migrations.AlterField(
            model_name='holdingelem',
            name='price_guaranteed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='保本价'),
        ),
        migrations.AlterField(
            model_name='holdingelem',
            name='profit',
            field=models.FloatField(default=0, verbose_name='盈亏'),
        ),
        migrations.AlterField(
            model_name='holdingelem',
            name='value',
            field=models.FloatField(default=0, verbose_name='市值'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.FloatField(blank=True, default=0, help_text='Total traded amount of this stock today', null=True, verbose_name='交易额'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='highest price of the stock till now today', max_digits=5, null=True, verbose_name='最高价'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='last price of the stock', max_digits=5, null=True, verbose_name='最新价'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='limit_down',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='limit down of the stock today', max_digits=5, null=True, verbose_name='跌停价'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='limit_up',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='limit up of the stock today', max_digits=5, null=True, verbose_name='涨停价'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='lowest price of the stock till now today', max_digits=5, null=True, verbose_name='最低价'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.IntegerField(blank=True, default=0, help_text='Total traded volume of this stock today', null=True, verbose_name='交易量'),
        ),
    ]
