# Generated by Django 2.2.2 on 2019-06-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20190622_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseclient',
            name='cash',
            field=models.FloatField(default=100000),
        ),
        migrations.AlterField(
            model_name='baseclient',
            name='flexible_cash',
            field=models.FloatField(default=100000),
        ),
        migrations.AlterField(
            model_name='baseclient',
            name='frozen_cash',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='baseclient',
            name='profit',
            field=models.FloatField(default=0, help_text='profit made till now'),
        ),
        migrations.AlterField(
            model_name='baseclient',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Activate'), ('f', 'forbidden'), ('i', 'Inactivate')], default='a', help_text='client status', max_length=1),
        ),
        migrations.AlterField(
            model_name='commissionelem',
            name='price_traded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='成交价格'),
        ),
        migrations.AlterField(
            model_name='commissionelem',
            name='vol_traded',
            field=models.IntegerField(default=0, verbose_name='成交数量'),
        ),
    ]
